name: Java CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to the Maven Central Repository
        run: mvn  -Dmaven.test.skip --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#      - name: Set up Java for publishing to GitHub Packages
#        uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'temurin'
#      - name: Publish to GitHub Packages
#        run: mvn  -Dmaven.test.skip --batch-mode deploy
#        env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
